.TH "Arcade::IAGhost" 3 "Tue Mar 27 2018" "Version 1.0" "ARCADE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::IAGhost
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIAGhost\fP (\fBColor\fP color, unsigned int x, unsigned int y, const std::string &pathSprite)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBArcade::Pixel\fP player, std::vector< \fBArcade::Pixel\fP > &_screen, bool eating)"
.br
.ti -1c
.RI "const \fBArcade::Pixel\fP & \fBgetGhost\fP () const"
.br
.ti -1c
.RI "void \fBsetGhost\fP (const \fBPixel\fP &ghost)"
.br
.ti -1c
.RI "void \fBsetSprite\fP (const std::string &sprite)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ARCADE from the source code\&.
