.TH "Arcade::LibraryLoader" 3 "Tue Mar 27 2018" "Version 1.0" "ARCADE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::LibraryLoader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBloadLibrary\fP (std::string libraryPath)"
.br
.ti -1c
.RI "void * \fBgetFunction\fP (void *handle, std::string functionName)"
.br
.ti -1c
.RI "void \fBcloseLibrary\fP (void *handle)"
.br
.ti -1c
.RI "bool \fBisLibraryOfType\fP (void *handle, const std::string &type)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ARCADE from the source code\&.
