.TH "Arcade::Core" 3 "Tue Mar 27 2018" "Version 1.0" "ARCADE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Core
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCore\fP (std::vector< std::shared_ptr< \fBArcade::ILibrary\fP >> _libraries, std::vector< std::shared_ptr< \fBArcade::IGame\fP >> _games, std::shared_ptr< \fBArcade::IMusic\fP > musicLibrary, unsigned int libraryIndex)"
.br
.ti -1c
.RI "void \fBcoreLoop\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ARCADE from the source code\&.
