.TH "Arcade::SFML" 3 "Tue Mar 27 2018" "Version 1.0" "ARCADE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::SFML
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBArcade::ILibrary\fP, and \fBArcade::IMusic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateWindow\fP ()"
.br
.ti -1c
.RI "void \fBdestroyWindow\fP ()"
.br
.ti -1c
.RI "Arcade::Input \fBgetInput\fP ()"
.br
.ti -1c
.RI "void \fBputPixel\fP (\fBArcade::Pixel\fP pixel)"
.br
.ti -1c
.RI "void \fBputText\fP (const \fBArcade::Text\fP &text)"
.br
.ti -1c
.RI "void \fBdrawBackground\fP (const std::string &backgroundPath)"
.br
.ti -1c
.RI "void \fBsendScore\fP (unsigned int score)"
.br
.ti -1c
.RI "void \fBdrawUserInterface\fP ()"
.br
.ti -1c
.RI "void \fBsendName\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBplaySound\fP (const std::string &path, bool loop, float volume)"
.br
.ti -1c
.RI "void \fBcleanSounds\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ARCADE from the source code\&.
