.TH "Arcade::IMusic" 3 "Tue Mar 27 2018" "Version 1.0" "ARCADE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::IMusic
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBArcade::SFML\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBplaySound\fP (const std::string &path, bool loop, float volume)=0"
.br
.ti -1c
.RI "virtual void \fBcleanSounds\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ARCADE from the source code\&.
